#!/bin/bash
# shellcheck disable=SC1091
source lib/repository.sh

process_value() { local resource="$1"; local key="$2"; local value="$3"
  case $key in
    _id)  show "$resource" "$value"        ; break ;;
    *  ) index "$resource" "$key" "$value" ; break ;;
  esac
}

menu_value() { local resource="$1"; key="$2"
  # read -r -p "Enter value for ${resource} ${key}: " value
  PS3="Select ${resource} ${key} value: "
  IFS=$'\n' values=($(values_for "$resource" "$key"))
  select value in "${values[@]}"; do
    IFS=' ' process_value "$resource" "$key" "$value"
    break
  done
}

menu_key() { local resource="$1"
  PS3="Select ${resource} key: "
  select key in $(keys_for "$resource"); do
    (menu_value "$resource" "$key" "$value")
    break
  done
}

menu_resource() {
  PS3="Select resource: "
  select resource in "${RESOURCES[@]}"; do
    (menu_key "$resource")
  done
}


echo "Welcome to Zendesk Search"
menu_resource
