#!/bin/bash
. lib/repository.sh

process_value() { local resource="$1"; local key="$2"; local value="$3"
  case $key in
    _id)  show "$resource" "$value"        ; break ;;
    *  ) index "$resource" "$key" "$value" ; break ;;
  esac
}

select_key() { local resource="$1"
  PS3="Select ${resource} key: "
  select key in $(keys_for "$resource"); do
    read -p "Enter value for ${resource} ${key}: " value
    process_value "$resource" "$key" "$value"
  done
}

select_resource() {
  PS3="Select resource: "
  select resource in users tickets organizations; do
    (select_key "$resource")
  done
}


echo "Welcome to Zendesk Search"
select_resource
