#!/bin/bash
# shellcheck disable=SC1091
source lib/repository.sh
source lib/menu.sh


show() {  local resource="$1"; local value="$2"
  clear
  find_ "$resource" "$value" |
    less --RAW-CONTROL-CHARS
}

process_value() { local resource="$1"; local key="$2"; local value="$3"
  clear
  case $key in
    _id)         show "$resource" "$value"        ; break ;;
    *  ) menu_find_by "$resource" "$key" "$value" ; break ;;
  esac
}

menu_find_by() { local resource="$1"; local key="$2"; local value="$3"
  IFS=$'\n' ids=($(find_by "$resource" "$key" "$value"))
  while selected="$(menu "\"/$resource?$key=$value"\" "${ids[@]}")"; do
    show "$resource" "${ids[$selected]}"
  done
}

menu_value() { local resource="$1"; local key="$2"
  IFS=$'\n' values=($(values_for "$resource" "$key"))
  while selected=$(menu "\"/$resource?$key="\" "${values[@]}"); do
    (process_value "$resource" "$key" "${values[$selected]}")
  done
}

menu_key() { local resource="$1";
  keys=($(keys_for "$resource"))
  while selected=$(menu "\"/$resource\"" "${keys[@]}"); do
    (menu_value "$resource" "${keys[$selected]}")
  done
}

menu_resource() {
  while selected="$(menu "\"/\"" "${RESOURCES[@]}")"; do
    (menu_key "${RESOURCES[$selected]}")
  done
}


menu_resource
